### ISSUE TITLE
getting an error of "Proc not found: D3D12GetInterface"

### ISSUE THREAD

**Issue by nommi** [soupstream/EldenRingStutterFix#2] opened 2022-03-16 01:15 UTC
Getting this error from lauching the game exe directly with EAC disabled, wasn't able to launch the game with this installed unfortunately.

**Comment by soupstream** [comment] 2022-03-16 02:40
I've published a new version that should fix this: https://github.com/soupstream/EldenRingStutterFix/releases/tag/v1.0.2

**Comment by soupstream** [comment] 2022-03-16 20:53
Which Windows 10 version are you on? (the number in Settings > System > About > Version)

**Comment by soupstream** [comment] 2022-03-17 00:43
Seems like this is a duplicate of https://github.com/soupstream/EldenRingStutterFix/issues/3, closing

**Closed by soupstream** 2022-03-17 00:43 UTC
